#!/bin/bash

# main_analyzer.sh - Shell-Guard 메인 분석 스크립트
# PR 변경사항 분석, 보안 스캔, 스타일 검사, AI 리뷰를 수행하고 결과를 GitHub PR에 댓글로 작성

set -e

# 환경 변수 로드
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config/env.sh"

# 모듈 로드
source "${SCRIPT_DIR}/modules/git_diff.sh"
source "${SCRIPT_DIR}/modules/scanner.sh"
source "${SCRIPT_DIR}/modules/style_checker.sh"
source "${SCRIPT_DIR}/modules/ai_helper.sh"
source "${SCRIPT_DIR}/modules/github_api.sh"

# ========================================
# 메인 분석 함수
# ========================================
main() {
    log_info "=== Shell-Guard Analysis Started ==="

    # 임시 디렉토리 생성
    create_tmp_dir

    # Trap 설정 (종료 시 임시 파일 정리)
    trap cleanup_tmp_dir EXIT

    # 필수 환경 변수 확인
    if ! check_required_env; then
        log_error "Required environment variables are missing"
        exit 1
    fi

    # 필수 도구 설치 확인
    check_jq_installed || exit 1
    check_curl_installed || exit 1

    log_info "Repository: ${REPO_OWNER}/${REPO_NAME}"
    log_info "PR Number: ${PR_NUMBER}"

    # ========================================
    # 1단계: Git Diff 추출
    # ========================================
    log_info "Step 1: Extracting Git diff..."
    if ! extract_diff; then
        log_error "Failed to extract diff"
        exit 1
    fi

    # ========================================
    # 2단계: 보안 스캔
    # ========================================
    log_info "Step 2: Running security scan..."
    run_security_scan
    security_status=$?

    # 보안 이슈 발견 시 즉시 처리
    if [ $security_status -eq 2 ]; then
        log_error "Critical security issues detected!"

        # 보안 이슈 리포트 생성
        generate_security_only_report

        # GitHub에 댓글 작성 및 변경 요청
        report_content=$(<"$FINAL_REPORT")
        post_pr_comment "$report_content"
        request_changes "🚨 보안 이슈가 발견되었습니다. 민감 정보를 제거해주세요."

        log_error "Analysis stopped due to security issues"
        exit 1
    fi

    # ========================================
    # 3단계: 스타일 검사
    # ========================================
    log_info "Step 3: Running style check..."
    run_style_check
    style_status=$?

    # ========================================
    # 4단계: AI 리뷰
    # ========================================
    log_info "Step 4: Running AI review..."
    run_ai_review || true
    ai_status=$?

    # ========================================
    # 5단계: 최종 리포트 생성
    # ========================================
    log_info "Step 5: Generating final report..."
    generate_final_report

    # ========================================
    # 6단계: GitHub PR에 댓글 작성
    # ========================================
    log_info "Step 6: Posting comment to GitHub PR..."
    report_content=$(<"$FINAL_REPORT")

    if ! post_pr_comment "$report_content"; then
        log_error "Failed to post comment to GitHub"
        exit 1
    fi

    log_success "=== Shell-Guard Analysis Completed Successfully ==="

    return 0
}

# ========================================
# 함수: 보안 이슈 전용 리포트 생성
# ========================================
generate_security_only_report() {
    log_info "Generating security-only report..."

    cat > "$FINAL_REPORT" <<EOF
### 🔍 Shell-Guard 자동 리뷰 결과

⚠️ **CRITICAL: 보안 이슈 감지**

이 PR에서 민감 정보가 발견되어 추가 분석이 중단되었습니다.

---

#### 🔐 보안 검사

$(format_scan_result_markdown)

---

**⚠️ 즉시 조치 필요:**
1. 모든 민감 정보를 코드에서 제거하세요
2. 발견된 키/토큰이 유출된 경우 즉시 폐기하고 새로 발급하세요
3. 환경 변수 또는 시크릿 관리 시스템을 사용하세요
4. 절대 커밋 히스토리에 민감 정보를 남기지 마세요

---

*Automatically generated by Shell-Guard*
EOF
}

# ========================================
# 함수: 최종 리포트 생성
# ========================================
generate_final_report() {
    log_info "Generating comprehensive report..."

    # 변경 요약 정보
    local diff_summary
    diff_summary=$(generate_diff_summary)

    # 보안 스캔 결과
    local security_result
    security_result=$(format_scan_result_markdown)

    # 스타일 검사 결과
    local style_result
    style_result=$(format_style_result_markdown)

    # AI 리뷰 결과
    local ai_result
    ai_result=$(format_ai_result_markdown)

    # 최종 리포트 작성
    cat > "$FINAL_REPORT" <<EOF
### 🔍 Shell-Guard 자동 리뷰 결과

---

#### 📌 변경 요약

$diff_summary

**변경된 파일 목록:**
\`\`\`
$(get_changed_files)
\`\`\`

---

#### 🔐 보안 검사

$security_result

---

#### 🧹 스타일 검사

$style_result

---

#### 🤖 AI 리뷰

$ai_result

---

#### 📊 분석 완료 시간

**분석 시각:** $(date '+%Y-%m-%d %H:%M:%S %Z')

---

*Automatically generated by Shell-Guard*
EOF

    log_success "Final report generated: $FINAL_REPORT"
}

# ========================================
# 메인 실행
# ========================================
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    main "$@"
    exit $?
fi
