#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config/env.sh"

source "${SCRIPT_DIR}/modules/git_diff.sh"
source "${SCRIPT_DIR}/modules/scanner.sh"
source "${SCRIPT_DIR}/modules/style_checker.sh"
source "${SCRIPT_DIR}/modules/ai_helper.sh"
source "${SCRIPT_DIR}/modules/github_api.sh"

main() {
    log_info "=== Shell-Guard Analysis Started ==="

    create_tmp_dir
    trap cleanup_tmp_dir EXIT

    check_required_env || exit 1
    check_jq_installed || exit 1
    check_curl_installed || exit 1

    log_info "Repository: ${REPO_OWNER}/${REPO_NAME}"
    log_info "PR Number: ${PR_NUMBER}"

    log_info "Step 1: Extracting Git diff..."
    extract_diff || exit 1

    log_info "Step 2: Running security scan..."
    run_security_scan
    security_status=$?

    if [ "$security_status" -eq 2 ]; then
        log_warning "Security issues detected"
    elif [ "$security_status" -eq 0 ]; then
        log_success "No security issues found"
    fi

    log_info "Step 3: Running style check..."
    run_style_check

    log_info "Step 4: Running AI review..."
    run_ai_review || true

    log_info "Step 5: Generating final report..."
    generate_final_report

    log_info "Step 6: Posting comment to GitHub PR..."
    report_content=$(<"$FINAL_REPORT")
    post_pr_comment "$report_content" || true

    if [ "$security_status" -eq 2 ]; then
        log_warning "Requesting changes due to security issues..."
        request_changes "🚨 보안 이슈가 발견되었습니다. PR 댓글의 상세 가이드를 확인하고 민감 정보를 제거해주세요." || true
    fi

    log_success "=== Shell-Guard Analysis Completed Successfully ==="
    exit 0
}

generate_final_report() {
    local diff_summary security_result style_result ai_result
    diff_summary=$(generate_diff_summary)
    security_result=$(format_scan_result_markdown)
    style_result=$(format_style_result_markdown)
    ai_result=$(format_ai_result_markdown)

    cat > "$FINAL_REPORT" <<EOF
### 🔍 Shell-Guard 자동 리뷰 결과

---

#### 📌 변경 요약

$diff_summary

**변경된 파일 목록:**
\`\`\`
$(get_changed_files)
\`\`\`

---

#### 🔐 보안 검사

$security_result

---

#### 🧹 스타일 검사

$style_result

---

#### 🤖 AI 리뷰

$ai_result

---

**분석 시각:** $(date '+%Y-%m-%d %H:%M:%S %Z')

*Automatically generated by Shell-Guard*
EOF
}

if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    main "$@"
fi
